### ISSUE TITLE
My friend can't join my world port

### ISSUE THREAD

**Issue by Hzkoh** [Nomifactory/ExtendedCrafting#39]
https://mclo.gs/zUar06s

**Comment by Exaxxion** [comment]
The stack trace is vanilla Minecraft (and one Forge) code paths, suggesting that this has nothing to do with ExtendedCrafting.

The disclaimer at the bottom of the log is just to remind you that you're using our fork of ExtendedCrafting, not the original mod: if the issue is explicitly related to ExtendedCrafting then you should report that bug here rather than to the original mod's repository.
